---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php for Ubuntu servers
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes