---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-apache
      state: latest
      update_cache: yes
    when ansible_distribution == "Ubuntu"

  - name: install apache and php for Rocky servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when ansible_distribution == "Rocky"